FROM golang:1.23-alpine AS build_base
RUN apk add --no-cache git
WORKDIR /src
ARG APP_VERSION

COPY . /src
WORKDIR /src
RUN go mod download
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=$APP_VERSION'" -trimpath -o bootstrap ./cmd/zipstash-server

FROM alpine:3.21
RUN apk add ca-certificates
COPY --from=build_base /src/bootstrap /app/bootstrap

ENTRYPOINT ["/app/bootstrap"]
