version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server --console-address ":9001" --address ":9000" /data
    expose:
      - "9000"
      - "9001"
    hostname: minio
    # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    user: 0:0
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodblocal:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
volumes:
  data:
  dynamodblocal:
