services:
  app:
    image: public.ecr.aws/docker/library/golang:1.23
    volumes:
      - ../:/work:cached
      - ~/.cache/go-build:/root/.cache/go-build
      - ~/go/pkg/mod:/go/pkg/mod
    working_dir: /work
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
