env:
  GOPATH: /root/go

steps:
  - group: ':mag: QA'
    id: quality_assurance
    steps:
    - key: go_mod_download
      commands:
        - go mod download
        - go build ./cmd/...
      label: ':golang: mod download and build'
      plugins:
        - wolfeidau/zipstash#main:
            id: go
            key: "{{ id }}-{{ checksum 'go.mod' }}"
            fallback-branch: main
            paths: |
              ~/go/pkg/mod
              ~/.cache/go-build
            endpoint: $ENDPOINT
            repo: wolfeidau/zipstash
            clean: true
    - key: lint
      label: ':golang: vet'
      command: go vet ./...
      plugins:
        - wolfeidau/zipstash#main:
            id: go
            key: "{{ id }}-{{ checksum 'go.mod' }}"
            fallback-branch: main
            paths: |
              ~/go/pkg/mod
              ~/.cache/go-build
            endpoint: $ENDPOINT
            repo: wolfeidau/zipstash
            clean: true
            skip-save: true
      depends_on: go_mod_download
    - key: test
      label: ':golang: test'
      command: go test -v -cover ./...
      plugins:
        - wolfeidau/zipstash#main:
            id: go
            key: "{{ id }}-{{ checksum 'go.mod' }}"
            fallback-branch: main
            paths: |
              ~/go/pkg/mod
              ~/.cache/go-build
            endpoint: $ENDPOINT
            repo: wolfeidau/zipstash
            clean: true
            skip-save: false
      depends_on: go_mod_download
