// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// CacheDownloadInstruction defines model for CacheDownloadInstruction.
type CacheDownloadInstruction struct {
	// Method HTTP method
	Method string  `json:"method"`
	Offset *Offset `json:"offset,omitempty"`

	// Url URL
	Url string `json:"url"`
}

// CacheEntry defines model for CacheEntry.
type CacheEntry struct {
	// Compression Compression algorithm
	Compression string `json:"compression"`

	// FileSize Size of the cache entry in bytes
	FileSize int64 `json:"file_size"`

	// Key Key of the cache entry
	Key string `json:"key"`

	// Paths Paths to upload the cache entry
	Paths []string `json:"paths"`

	// Sha256sum SHA256 checksum of the cache entry
	Sha256sum string `json:"sha256sum"`

	// Url URL to upload the cache entry
	Url *string `json:"url,omitempty"`
}

// CacheEntryCreateRequest defines model for CacheEntryCreateRequest.
type CacheEntryCreateRequest struct {
	CacheEntry CacheEntry `json:"cache_entry"`

	// MultipartSupported multipart supported
	MultipartSupported bool `json:"multipart_supported"`
}

// CacheEntryCreateResponse defines model for CacheEntryCreateResponse.
type CacheEntryCreateResponse struct {
	// Id Upload ID
	Id                 string                   `json:"id"`
	Multipart          bool                     `json:"multipart"`
	UploadInstructions []CacheUploadInstruction `json:"upload_instructions"`
}

// CacheEntryGetResponse defines model for CacheEntryGetResponse.
type CacheEntryGetResponse struct {
	CacheEntry           CacheEntry                 `json:"cache_entry"`
	DownloadInstructions []CacheDownloadInstruction `json:"download_instructions"`
	Multipart            bool                       `json:"multipart"`
}

// CacheEntryUpdateRequest defines model for CacheEntryUpdateRequest.
type CacheEntryUpdateRequest struct {
	// Id Upload ID
	Id string `json:"id"`

	// Key Key of the cache entry
	Key string `json:"key"`

	// MultipartEtags ETags
	MultipartEtags []CachePartETag `json:"multipart_etags"`
}

// CacheEntryUpdateResponse defines model for CacheEntryUpdateResponse.
type CacheEntryUpdateResponse struct {
	// Id Response ID
	Id string `json:"id"`
}

// CachePartETag Part index and ETag
type CachePartETag struct {
	// Etag ETag
	Etag string `json:"etag"`

	// Part Part index
	Part     int32 `json:"part"`
	PartSize int64 `json:"part_size"`
}

// CacheUploadInstruction defines model for CacheUploadInstruction.
type CacheUploadInstruction struct {
	// Method HTTP method
	Method string  `json:"method"`
	Offset *Offset `json:"offset,omitempty"`

	// Url URL
	Url string `json:"url"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Offset defines model for Offset.
type Offset struct {
	// End End position of the part
	End int64 `json:"end"`

	// Part Part number
	Part int32 `json:"part"`

	// Start Start position of the part
	Start int64 `json:"start"`
}

// CreateCacheEntryJSONRequestBody defines body for CreateCacheEntry for application/json ContentType.
type CreateCacheEntryJSONRequestBody = CacheEntryCreateRequest

// UpdateCacheEntryJSONRequestBody defines body for UpdateCacheEntry for application/json ContentType.
type UpdateCacheEntryJSONRequestBody = CacheEntryUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates a cache entry
	// (POST /v1/cache/{provider})
	CreateCacheEntry(ctx echo.Context, provider string) error
	// Updates a cache entry
	// (PUT /v1/cache/{provider})
	UpdateCacheEntry(ctx echo.Context, provider string) error
	// Get a cache entry by key
	// (GET /v1/cache/{provider}/{key})
	GetCacheEntryByKey(ctx echo.Context, provider string, key string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateCacheEntry converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCacheEntry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCacheEntry(ctx, provider)
	return err
}

// UpdateCacheEntry converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCacheEntry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCacheEntry(ctx, provider)
	return err
}

// GetCacheEntryByKey converts echo context to params.
func (w *ServerInterfaceWrapper) GetCacheEntryByKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", ctx.Param("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCacheEntryByKey(ctx, provider, key)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/cache/:provider", wrapper.CreateCacheEntry)
	router.PUT(baseURL+"/v1/cache/:provider", wrapper.UpdateCacheEntry)
	router.GET(baseURL+"/v1/cache/:provider/:key", wrapper.GetCacheEntryByKey)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RX23LbNhD9FQzaRyai5EtbvTWOx/Ek03gS+ynj8cDkSkQtAgiwdEx7+O8dACTFCyRZ",
	"bd3rm0Qscc6ePVgsn2gicyUFCDR0/kRNkkHO3M8TlmTwVn4TK8nSc2FQFwlyKeya0lKBRg4uMgfMZGp/",
	"pWASzZUPo+8uLy9IvRhRLBXQOTWouVjSKqJysTCA9rXvNSzonH43WZOZ1EwmH31UFdFCr8YYV58+jPeu",
	"Iqrha8E1pHT+xb0YNSyvq8indipQl+NkLAUNxtSZ9tFO1ouErZZSc8xyGlF4YLlaWQrLR64sGBcfQCwx",
	"o/ODQOoLvoIbwx9hDPGZPwKRC4IZkMTyJGCJEi7IbYlgumjTeBbRhdQ5QzqnXODxocfmeZHT+bRF5gJh",
	"CdpC30E5Bn0PZQCzl1hevnJLr5qlTorTQIqKYWbGSBf2MUFJCmV9FYDkCLl7cbRlzsW5X1wDMq1ZaRdN",
	"xmZHx8bmPZL03c+zo2OSZJDcmSLflel0dnB4dPzDjz/F7DZJYbHv/742x4cBcTZZeaswWwUfWN5WuWuz",
	"qOfrrlpNpfrn4kQDQ/gEXwswGDgkNvAGmhO07fx2zpotYbFCrpjGG1MoJTVCoG+0QWQd1CZ8K+UKmBhl",
	"HNo56hENZ2iUFAbGKfIAsStfmvO3oXbWEuh4tyUbUV/WG75upB6mcftODT14txFXw1MwkIRbBUK4XbJ9",
	"Vc4AN0vyu6ue1rfIH8g+dBFV4y6wtQgDebrpbOK4WakrlW47IXvb56/qy+tzAsiWgQ59emkfR3vU5oJp",
	"tG/t6NEhd/o+NeQUVnqfk9pEB8UeE2kB21QCF5dGwkUKD4SJlLigaMDEsg8L+pz70pt2Eyrt3/QHs503",
	"vW+G9ZAxmhKG8QNRHJ3IZ9TdqlVq3I7+/XPhqdZSh0bCNDCouWDi1gKlGZcjB2PYcuNGzfIu0jVgE25p",
	"f2wFG9hRBMQ/FSlR0nD7t+ktdbH3nCS3OFYU+S3ooGXZQ71lHMfxLgiDQYzP9vH+WcQ7Xe/xIqdcneB1",
	"ZYO4WEh3pXB0XfeRK2KQmYwY0Pcu1XvQ/qOBTl/Hr2PnZAWCKU7n9MA96kzFk/vpxPXtyZPS8p6noCtX",
	"QelvE1tHZrM7T+13hxtWOpeqI8dyQNCGzr8MBfqF5e1HRLP9a9vT7aLlQCMqWG4zaZZpVwnUBUT1x2Bg",
	"FK+ufTAYfCPT0p8RgSAcdabUiieO/ORX4xvDeqvnTQ39+bOqfKF8T3f6zeLpC8LWV42D7Svrr+GGCvnG",
	"MWsm9t7g4F5csGKFfxpN350CnAoBDwoShJRAHRNRU+Q5s4NabR5DWG+GsAe4CFjN37b/I6v1B7mg1eIX",
	"hP1PWc0nNbJaFQX73eTpDkrX9ZYQcOIZ4FquN+V7+Nu9GD2FtvIz7J6OfnF/db/knmmuQXv4p5jqDLBv",
	"KHJbEiu6Pau/BQAA///PFBDzwRQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
